export const fields = {
  name: '机构名称',
  type: '机构类型',
  orgCode: '统一社会信用代码',
  dwellArea: '省市区',
  dwellAddress: '详细地址',
  orgEmail: '公司邮箱',
  orgTelephone: '公司电话',
  logoImage: '公司Logo',
  licenseImage: '营业执照图片',
  bank: '开户银行',
  orgAccount: '收款账户',
  accountName: '收款户名',
  orgLegal: '公司法人',
  legalCertNo: '法人证件号码',
  legalTelephone: '法人手机号',
  orgAgent: '经办人',
  legalImage1: '法人身份证正面',
  legalImage2: '法人身份证背面',
  agentCertNo: '经办人证件号码',
  agentTelephone: '经办人手机号',
  agentImage1: '经办人身份证正面',
  agentImage2: '经办人身份证背面'
}
