export const DetailFields = {
  cId: '保全编号',
  cCourt: '申请法院',
  courtType: '保全类型',
  courtCategory: '保全类别',
  cCaseType: '案件类型',
  cCaseNo: '案号',
  caseYear: '年份',
  caseCode: '法院代字',
  caseZips: '案件类型代字',
  codeOrder: '案件序号',
  cCaseReason: '案由',
  cCaseReason2: '案由',
  cCaseReasonMain: '主体案由',
  cCaseReasonAction: '行为案由',
  cMoney: '保全金额',
  guaranteeCase: '	担保情况',
  noGuaranteeReason: '无需担保原因',
  cIssueStatus: '提交人身份',
  cDesc: '备注',
  step: '	创建步骤',
  cStatus: '保全状态'
}
